openapi: 3.0.1
info:
  title: test proxy
  version: 0.1.0
servers:
  - url: '{server}:{port}/'
    variables:
      server:
        default: http://localhost
      port:
        default: '9090'
security:
  - default: []
paths:
  /lov/lovs/{lovtype}:
    get:
      operationId: getLovLovsLovtype
      parameters:
        - name: lovtype
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        '500':
          description: InternalServerError
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetail'
        default:
          description: Any Response
          content:
            '*/*':
              schema:
                description: Any type of entity body
      security:
        - default: []
      x-throttling-tier: Unlimited
      x-throttling-limit:
        requestCount: -1
        unit: MINUTE
  /lov/countries:
    get:
      operationId: getLovCountries
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Countries'
        '500':
          description: InternalServerError
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetail'
      security:
        - default: []
      x-throttling-tier: Unlimited
      x-throttling-limit:
        requestCount: -1
        unit: MINUTE
  /lov/locations:
    get:
      operationId: getLovLocations
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Locations'
        '500':
          description: InternalServerError
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetail'
      security:
        - default: []
      x-throttling-tier: Unlimited
      x-throttling-limit:
        requestCount: -1
        unit: MINUTE
components:
  schemas:
    ErrorDetail:
      required:
        - message
      type: object
      properties:
        message:
          type: string
    CountryArray:
      required:
        - country
      type: object
      properties:
        country:
          type: array
          items:
            $ref: '#/components/schemas/Country'
    Countries:
      required:
        - countries
      type: object
      properties:
        countries:
          $ref: '#/components/schemas/CountryArray'
    LocationArray:
      required:
        - location
      type: object
      properties:
        location:
          type: array
          items:
            $ref: '#/components/schemas/Location'
    Locations:
      required:
        - locations
      type: object
      properties:
        locations:
          $ref: '#/components/schemas/LocationArray'
    Country:
      required:
        - bessemerCd
        - commisionRate
        - currencyName
        - euMember
        - fipsCd
        - isoCd
        - isoCurrencyCd
        - name
        - regionCd
        - regionCommissionRate
        - regionName
        - riskLevel
        - riskRank
        - taxCd
      type: object
      properties:
        bessemerCd:
          type: string
          nullable: true
        regionCommissionRate:
          type: string
          nullable: true
        isoCurrencyCd:
          type: string
          nullable: true
        riskLevel:
          type: string
          nullable: true
        riskRank:
          type: string
          nullable: true
        regionName:
          type: string
          nullable: true
        fipsCd:
          type: string
          nullable: true
        commisionRate:
          type: string
          nullable: true
        regionCd:
          type: string
          nullable: true
        currencyName:
          type: string
          nullable: true
        name:
          type: string
          nullable: true
        isoCd:
          type: string
          nullable: true
        taxCd:
          type: string
          nullable: true
        euMember:
          type: string
          nullable: true
    Location:
      required:
        - depoId
        - depoStorageAcctNo
        - locationCode
        - locationId
        - locationIdGp
        - locationName
      type: object
      properties:
        locationName:
          type: string
          nullable: true
        depoId:
          type: string
          nullable: true
        locationId:
          type: string
          nullable: true
        locationIdGp:
          type: string
          nullable: true
        locationCode:
          type: string
          nullable: true
        depoStorageAcctNo:
          type: string
          nullable: true
  securitySchemes:
    default:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://test.com
          scopes: {}
x-wso2-disable-security: false
x-wso2-auth-header: Authorization
x-wso2-cors:
  corsConfigurationEnabled: false
  accessControlAllowOrigins:
    - '*'
  accessControlAllowCredentials: false
  accessControlAllowHeaders:
    - authorization
    - Access-Control-Allow-Origin
    - Content-Type
    - SOAPAction
    - apikey
    - API-Key
    - testKey
  accessControlAllowMethods:
    - GET
    - PUT
    - POST
    - DELETE
    - PATCH
    - OPTIONS
x-wso2-production-endpoints:
  urls:
    - http://localhost:9090
  type: http
x-wso2-sandbox-endpoints:
  urls:
    - http://localhost:9090
  type: http
x-wso2-basePath: /aa09155e-7c66-4eba-8f39-b32862014891/qoiz/restservicetest/v1.0
x-wso2-transports:
  - http
  - https
x-wso2-response-cache:
  enabled: false
  cacheTimeoutInSeconds: 300
